library frc;

uses
  Forms,
  addn in 'addn.pas',
  frm in 'FRM.PAS' {MainForm},
  geom in 'geom.pas',
  towrd in 'towrd.pas',
  dev in 'dev.pas',
  smez in 'smez.pas' {fSmez},
  about in 'ABOUT.PAS' {AboutBox},
  medit in 'medit.pas',
  linear in 'linear.pas' {fLinear},
  setup in 'setup.pas' {fSetup},
  selstyle in 'selstyle.pas' {fSelectStyle},
  explicator in 'explicator.pas',
  fieldsetup in 'fieldsetup.pas' {fFieldSetup},
  templateslist in 'templateslist.pas' {fTemplatesList},
//  protect in '..\..\..\Program Files\Borland\Delphi6\Projects\testproj\protect.pas' {fProtect},
  packetprint in 'packetprint.pas' {fPacketPrint};

{$R *.RES}

begin
end.
